import { Propiedad } from "../models/index.js";

const propiedades = [
  // insert 10 properties
  {
    titulo: "Casa de Lujo en el Lago",
    precio: 1000000,
    descripcion: "Casa de lujo con acceso al lago, excelente vista y ubicacion",
    habitaciones: 4,
    wc: 3,
    estacionamiento: 3,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_1.jpg",
    categoriaId: 1,
    usuarioId: 20,
  },
  {
    titulo: "Casa terminados de lujo",
    precio: 500000,
    descripcion: "Casa con acabados de lujo, en la mejor zona de la ciudad",
    habitaciones: 3,
    wc: 2,
    estacionamiento: 2,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_2.jpg",
    categoriaId: 1,
    usuarioId: 20,
  },
  {
    titulo: "Casa con alberca",
    precio: 300000,
    descripcion: "Casa con alberca y acabados modernos",
    habitaciones: 3,
    wc: 2,
    estacionamiento: 2,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_3.jpg",
    categoriaId: 1,
    usuarioId: 20,
  },
  {
    titulo: "Casa de campo",
    precio: 200000,
    descripcion: "Casa en el campo, ideal para el descanso",
    habitaciones: 2,
    wc: 1,
    estacionamiento: 2,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_4.jpg",
    categoriaId: 1,
    usuarioId: 20,
  },
  {
    titulo: "Casa con vista al bosque",
    precio: 400000,
    descripcion:
      "Casa con vista al bosque, acabados de lujo y amplios espacios",
    habitaciones: 4,
    wc: 3,
    estacionamiento: 3,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_5.jpg",
    categoriaId: 1,
    usuarioId: 20,
  },
  {
    titulo: "Departamento en el centro",
    precio: 300000,
    descripcion:
      "Departamento en el centro de la ciudad, con excelente ubicacion",
    habitaciones: 3,
    wc: 2,
    estacionamiento: 2,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_6.jpg",
    categoriaId: 2,
    usuarioId: 20,
  },
  {
    titulo: "Departamento con alberca",
    precio: 400000,
    descripcion: "Departamento con alberca y una hermosa vista al mar",
    habitaciones: 2,
    wc: 1,
    estacionamiento: 2,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_7.jpg",
    categoriaId: 2,
    usuarioId: 20,
  },
  {
    titulo: "Departamento de lujo",
    precio: 500000,
    descripcion: "Departamento de lujo con acabados modernos",
    habitaciones: 2,
    wc: 1,
    estacionamiento: 2,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_8.jpg",
    categoriaId: 2,
    usuarioId: 20,
  },
  {
    titulo: "Departamento con vista",
    precio: 200000,
    descripcion: "Departamento con una excelente vista a la ciudad",
    habitaciones: 2,
    wc: 1,
    estacionamiento: 2,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_9.jpg",
    categoriaId: 2,
    usuarioId: 20,
  },
  {
    titulo: "Departamento en la playa",
    precio: 600000,
    descripcion: "Departamento con vista al mar, excelente ubicacion",
    habitaciones: 3,
    wc: 2,
    estacionamiento: 2,
    lat: "19.431940",
    lng: "-99.133217",
    imagen: "imagen_10.jpg",
    categoriaId: 2,
    usuarioId: 20,
  },
];

export default propiedades;
